{
 "title": "CTFd3",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Host metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Host: $node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
      }
     ]
    }
   ]
  },
  { "title": "Host status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "Host", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Hostname", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"nginx\",exporter_name=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"ctfd\",exporter_name=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"cache\",exporter_name=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"db\",exporter_name=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"elk\",exporter_name=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"localhost:9090\"}",
     "legendFormat": "prom"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"backup\",exporter_name=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Docker", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"nginx\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"stopped\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"nginx\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"running\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"ctfd\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"stopped\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"ctfd\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"running\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"cache\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"stopped\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"cache\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"running\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"db\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"stopped\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"db\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"running\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"elk\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"stopped\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"elk\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"running\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"prom\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"stopped\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"prom\",exporter_name=\"docker_exporter\", job=\"other_exporters\", state=\"running\"}",
     "legendFormat": "{{instance}}:"
    }
   ]
  },
  { "title": "Database", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Mysql instance up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}:" }
   ]
  },
  { "title": "Resources", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  { "title": "CPU", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 15 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"nginx\", job=\"other_exporters\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',exporter_name=\"node_exporter\", instance=\"nginx\", job=\"other_exporters\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"nginx\", job=\"other_exporters\"}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"ctfd\", job=\"other_exporters\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',exporter_name=\"node_exporter\", instance=\"ctfd\", job=\"other_exporters\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"ctfd\", job=\"other_exporters\"}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"cache\", job=\"other_exporters\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',exporter_name=\"node_exporter\", instance=\"cache\", job=\"other_exporters\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"cache\", job=\"other_exporters\"}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"db\", job=\"other_exporters\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',exporter_name=\"node_exporter\", instance=\"db\", job=\"other_exporters\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"db\", job=\"other_exporters\"}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"elk\", job=\"other_exporters\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',exporter_name=\"node_exporter\", instance=\"elk\", job=\"other_exporters\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"elk\", job=\"other_exporters\"}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"localhost:9090\", job=\"other_exporters\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',exporter_name=\"node_exporter\", instance=\"localhost:9090\", job=\"other_exporters\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"localhost:9090\", job=\"other_exporters\"}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"backup\", job=\"other_exporters\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',exporter_name=\"node_exporter\", instance=\"backup\", job=\"other_exporters\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{exporter_name=\"node_exporter\", instance=\"backup\", job=\"other_exporters\"}) by (cpu))"
    }
   ]
  },
  { "title": "RAM", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 16 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"nginx\"} * 100) / node_memory_MemTotal_bytes{instance=\"nginx\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"ctfd\"} * 100) / node_memory_MemTotal_bytes{instance=\"ctfd\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"cache\"} * 100) / node_memory_MemTotal_bytes{instance=\"cache\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"db\"} * 100) / node_memory_MemTotal_bytes{instance=\"db\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"elk\"} * 100) / node_memory_MemTotal_bytes{instance=\"elk\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"localhost:9090\"} * 100) / node_memory_MemTotal_bytes{instance=\"localhost:9090\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"backup\"} * 100) / node_memory_MemTotal_bytes{instance=\"backup\"})"
    }
   ]
  },
  { "title": "Volume", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 17 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"ctfd\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"elk\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"elk\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"localhost:9090\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"localhost:9090\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"backup\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"backup\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  }
 ]
}